# Day 14 – NumPy Matrix Operations

## AI & ML Internship – Day 14

This notebook demonstrates basic matrix operations using NumPy, including:

- Matrix Addition
- Matrix Subtraction
- Element-wise Multiplication
- Matrix Multiplication
- Matrix Transpose

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 1. Matrix Addition

Matrix addition is performed by adding corresponding elements
of two matrices.

In [3]:
addition = A + B

print("Matrix Addition:")
print(addition)

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


## 2. Matrix Subtraction

Matrix subtraction is performed by subtracting corresponding
elements of one matrix from another.

In [4]:
subtraction = A - B

print("Matrix Subtraction:")
print(subtraction)

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


## 3. Element-wise Multiplication

Element-wise multiplication multiplies corresponding elements
of two matrices.

In [5]:
elementwise_multiplication = A * B

print("Element-wise Multiplication:")
print(elementwise_multiplication)

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


## 4. Matrix Multiplication

Matrix multiplication is different from element-wise multiplication.
It follows the row-by-column multiplication rule.

For two matrices A and B, the number of columns in A must be equal
to the number of rows in B.

In [6]:
matrix_multiplication = A @ B

print("Matrix Multiplication:")
print(matrix_multiplication)

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [7]:
matrix_multiplication_dot = np.dot(A, B)

print("Matrix Multiplication using np.dot():")
print(matrix_multiplication_dot)

Matrix Multiplication using np.dot():
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## 5. Matrix Transpose

The transpose of a matrix changes its rows into columns
and its columns into rows.

In [8]:
transpose_A = A.T

print("Transpose of Matrix A:")
print(transpose_A)

Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

Shape of A: (3, 3)
Shape of B: (3, 3)
